version: "2"

services:
  api:
    restart: always
    build: ./api
    hostname: gcrawler-api
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/johnny/GCRAWLER/data:/data/
      - /home/johnny/GCRAWLER/GoogleSearchEmailCrawler/db.sqlite3:/app/db.sqlite3
    ports:
      - "5766:8000"
    container_name: gcrawler-api
    #command: python manage.py runserver 0.0.0.0:8000
    command: bash -c "uwsgi --ini uwsgi.ini"
    networks:
      - gcrawler-net
    logging:
      driver: json-file
      options:
        max-size: 10m

  web:
    restart: always
    build: ./web
    hostname: gcrawler-web
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "5767:3000"
    container_name: gcrawler-web
    command: npm run start
    #tty: true
    networks:
      - gcrawler-net
    logging:
      driver: json-file
      options:
        max-size: 10m

  crawler:
    restart: always
    build: ./crawler
    hostname: gcrawler-crawler
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/johnny/GCRAWLER/data:/data/
    container_name: gcrawler-crawler
    #tty: true
    command: python -c "import test_google; test_google()"
    networks:
      - gcrawler-net
    logging:
      driver: json-file
      options:
        max-size: 10m

networks:
  gcrawler-net:
