# Generated by Django 2.0.7 on 2018-10-15 08:36

from django.db import migrations, models
import shop.api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('query_url', models.CharField(max_length=500)),
                ('skip_url', models.CharField(max_length=500)),
                ('total_count', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
                ('status', models.CharField(default=shop.api.models.StatusType('INSCHEDULED'), max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
